### ISSUE TITLE
Once I make selection, it throws error that channel is not responding

### ISSUE THREAD

**Issue by emphaticsunshine** [coder-alpha/DesiTelly.bundle#2]
Attached screenshot of the above mentioned error. I am running it inside chrome on Mac OSX.

![image](https://cloud.githubusercontent.com/assets/1434091/21166407/05719e1c-c16b-11e6-85e8-7b1053a1953a.png)

**Comment by coder-alpha** [comment]
Please try after a PMS restart. Channel log files would be helpful.
