### ISSUE TITLE
I am not able to warch this channel... Video stopping every 30 seconds

### ISSUE THREAD

**Issue by rdudeja1133** [coder-alpha/DesiTelly.bundle#3]

**Comment by coder-alpha** [comment]
More info required.
Logs with reproduced error and info on client. 
It seems more like a client issue or network since this channel is used daily by friends.

**Comment by rdudeja1133** [comment]
Please see attached log. Also my internet down load speed is 76 MBPS and upload speed is 10.1 MBPS... It is buffering after ever 30 -40 seconds


[cid:20f38586-be66-4476-8721-a1ae4e807759]


Regards

RD

________________________________

**Comment by coder-alpha** [comment]
I didnt receive the logs. But if its a buffering issue (not a video stopping issue) then its probably outside the workings of the plugin.

The speed between your PMS and the video host is what matters. Using dailymotion try out 
1. Using Plex-web
2. Using the version with the lowest resolution

If either works try increasing your buffer size on the client.
or
Force transcoding and increase buffer on PMS.

![image](https://cloud.githubusercontent.com/assets/10291660/26371562/1ae9ec04-3fc9-11e7-8664-6539dbe83efb.png)

![image](https://cloud.githubusercontent.com/assets/10291660/26371605/33da3dae-3fc9-11e7-87c1-f4c61629805d.png)

**Comment by rdudeja1133** [comment]
I watch only 1 show on SONY... Sankat Mochan Hanuman.... Since last few weeks, I am not able to use Daily motion. Only "Watch Video HD" is working but stopping every 30 sec.....My network is same as before. 75MBPS download speed and 10 MBPS upload. I am able to stream enthusan, Netflix and other channels on my roku...


Regards

RD




________________________________

**Comment by coder-alpha** [comment]
Please try v. 0.07. Added new site and new host Vid-Watch which seems faster.
