### ISSUE TITLE
YoDesi (Speedwatch & Watch VideoHd) links are not working

### ISSUE THREAD

**Issue by ram2141** [coder-alpha/DesiTelly.bundle#5]
Speedwatch & WatchVideoHd links are not working for all TV Shows. No Content Error. Please update the script.

**Comment by coder-alpha** [comment]
SpeedWatch is fixed in [ver. 0.12](https://github.com/coder-alpha/DesiTelly.bundle/releases/tag/v0.12). Please test and confirm here.

WatchVideo worked fine on testing, please re-confirm. If issue persists, please post Show/Date and also logs would be helpful.

Cheers

**Comment by ram2141** [comment]
Thank you @coder-alpha. You are the best. It's working now.
