### ISSUE TITLE
Speedwatch.us is missing from all the channels 

### ISSUE THREAD

**Issue by ram2141** [coder-alpha/DesiTelly.bundle#6]
Speedwatch.us is missing from all the channels. And other video sources are not working as well like Google HD video, TunePK HD, Vidoza, Vidwatch and watchvideo HD. 

Vidoza buffers a lot. I have tried using 480p but still it's buffering. I never had any problem like this before but after updating plex media server and started all this issues. Any solution @coder-alpha . Thanks in Advance.

**Comment by coder-alpha** [comment]
It will only show the hosts that are provided by the site for that particular show. Nothing the plugin can do. Some of the other hosts are working but YMMV. The Google link is actually not google and some other site. Will look into this in a day or so.

**Comment by ram2141** [comment]
Thank you so much @coder-alpha for your help and time.

**Comment by coder-alpha** [comment]
Ver 0.13 is up - https://github.com/coder-alpha/DesiTelly.bundle/releases/tag/v0.13

All hosts should now be working. Let me know if there is a specific issue.
